### ISSUE TITLE
Different mobile keyboards are displayed depending on the field to fill in Monujo

### ISSUE THREAD

**Issue by stephansainleger** [Lokavaluto/monujo#251]
<p>Scenario:</p><ul><li><p>Marie-Odile (Pive) registered a comchain password</p></li><li><p>when she wants to pay, a different keyboard is displayed when she has to fill her password: she can't access to some characters ("£" for instance), then can't pay.<br></p></li></ul><p>Expecting behavior: have always the same keyboards displayed, except if some fields require specific digits (integer only for instance).<br></p><p>Reproducible on Android 7.1.1 and 8.0.0<br></p>

**Comment by seegwen** [comment]
This really seems to be a configuration detail on the user's device side.
We have a `type="text"` input for the email and the all-classical `type="password"` input for the password.
I'm sorry if this might seem pedantic, but I'm pretty sure the `£` character is somewhere hidden in the Odile's keyboard.
I can witness such behaviour on my own Android kbd where some chars are hidden in sub-keyboards whenever there is not enough room for them to be layout on the main one. This happens when my kbd displays some extra stuff on the first row.
There is no way in html / hybrid (like capacitor enables to do for the mobile app) for us to control what the keyboard on the user's device will be. It's entirely up to the Android flavour which is installed on the user's device.
The only thing we can do is make sure the field when registering and the field when authenticating are the same for the password, in order to maximize the chances the keyboard will be the same and the user does not get lost.

This might be of some help to Odile:
https://www.techindulge.com/how-to/hidden-symbols-android-phone-keyboard/

@stephansainleger 
https://dev2.lokavaluto.fr/web/signup is this the correct URL (in this case for dev3) where a user registers his password ?
If so, then we already have done what we can.

**Comment by vaab** [comment]
closed as it is a wontfix
