### ISSUE TITLE
The resources, android and ios directories are not related to the webapp and should not be included in the Monujo repo

### ISSUE THREAD

**Issue by seegwen** [Lokavaluto/monujo#255]

**Comment by vaab** [comment]
I'm interested by the rationale behind, and where you want to put them. I had the same reflex than you, but it seems that:
(cf: https://stackoverflow.com/questions/63084828/gitignore-for-an-ionic-project-with-android-target )
```
In Capacitor you are supposed to commit the ios and android folders. They contain their own .gitignore files with the recommended files for iOS and Android.

They are not build artifacts, if you change icons or configurations (in Info.plist, AndroidManifest.xml, etc) and you delete the folders, those changes will be lost.
```

**Comment by seegwen** [comment]
Thanks for the answer and the link.

Several points motivated me to report an issue:
- The fact that Monujo is at its hear a pure web app (which it might not be for long once we throw in fingerprint ID I reckon).

- There are some things in those directories (namely the icons, splashscreens, config files), which are dependant of the "flavour" (Vanilla, Pive, Roue) of Monujo we are building. Those assets need commands to be run in order for them to be properly set up (`cordova-res --skip-config --copy` & some manual file editing because of bug in `cordova-res`- cf https://docs.lokavaluto.fr/-OIGhbSLQLm44poywAYPkw#21-G%C3%A9n%C3%A9rer-les-iconessplashscreens ). So my idea while creating this issue was to start with a clean slate and have a full a-Z process to build the app.

- @stephansainleger had to remove the android directory and reinstall android capacitor plugin to be able to run/build it in his own android studio. In short he could not open the files I commited to the repo...

I understand what is said in the links you refer to, so I'm really wandering now but I'm still more in favour of not commiting the android and ios directories, but keeping capacitor as a `package.json` dep and keeping `capacitor.config.ts` commited, allthough it contains data that should be altered depending on the flavour of Monujo we are building.

Really interested to know what you think of all this, as I cannot make myself up.

**Comment by vaab** [comment]
De facto we stayed with `android` and `ios` app inside the root folder. I think with hindsight that this was a good default choice:
- We had several tweaking concerning signatures on `ios` in huge files that I'm happy to be able to review each change because of how inconsiderate each graphical tool of both platform seem keen to make unnecessary changes here and there.
- This code is our app code, and if `android` folder have to be reconstructed to fit a specific dev's config, that's an indicator that the dev is doing something wrong as this exact code is the one that build on all other's dev and on the CI infrastructure. We actually never had had this issue to my knowledge (except this case).
- I doubt that we can reconstruct it (it could be worth to try), but we have had several case of adding a line inside `ios` or `android` files to fix an issue. For a permission, modification of pod files, removal of orientations... etc ...

I'll close this as for now it doesn't seem to be an issue.
