### ISSUE TITLE
All routing to "/" is not resetting the store like logout

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#48]
We probably need to reset the store in each routeur call to "/". I guess this could be an action that call the actual logout mutation.

I have moments where buttons on the top are remaining.

Same idea: if I type "/profile", or "/create-account" in the URL bar, some of these pages will be displayed even if I'm not logged in.

**Comment by seegwen** [comment]
The "disconnect" button does not actually disconnect / reset auth.
Instead it is a vue-router link to the / route and the / route is the login page.
The router-link has a @click="logout" prop, but it is not triggered since the vue-router link has precedence.
The fix is to remove the router-link, make the @click event actually call the logout method in the Nav component, which will in turn call the askLogout action on the store and from there on we have the choice to:
a) call the requestLogin on the lokapiService directly from the askLogout action of the store
b) call the login route from the Nav component.
